name: Build and Deploy

on:
  push:
    branches:
      - master  # Change this to your main branch name if it's different

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Use Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14.x'
        
    - name: Install dependencies
      run: npm install
      
    - name: Build React app
      run: npm run build
      
    - name: Upload to S3
      uses: jakejarvis/s3-sync-action@master
      with:
        args: --delete
      env:
        AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        SOURCE_DIR: 'build'

    - name: Open S3 website in new tab
      run: |
        echo "<script>window.open('http://sakthivel-murugan-portfolio-react-721221106084.s3-website.ap-south-1.amazonaws.com', '_blank');</script>" > open_tab.html
      shell: bash

    - name: Display open_tab.html
      run: cat open_tab.html
